services:
 mysql:
   image: mysql:8
   container_name: mysqlcontainer
   ports:
      - 3307:3306
   environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: jfsaprdb
   networks:
    - productrest-network
   healthcheck:
     test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
     interval: 10s
     timeout: 5s
     retries: 5
 product-api:
   image: productrestjwt:2.0
   build: .
   container_name: product-container
   ports:
     - "8093:8081"
   depends_on:
    mysql:
     condition: service_healthy
   networks:
     - productrest-network  
networks:
 productrest-network:
    driver: bridge
  